# -*- coding: utf-8 -*-
"""Hands-on Lab: Interactive Visual Analytics with Folium.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZK4ZuDq-_MqHwzfvBwxwA57hsyO3WOt
"""

get_ipython().system('pip install folium')
get_ipython().system('pip install pandas')

import folium
import pandas as pd

# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library

# define the world map
world_map = folium.Map()

# display world map
world_map

import requests
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = requests.get(URL)
spacex_csv_file = io.BytesIO(resp.content)
spacex_df=pd.read_csv(spacex_csv_file)

# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)
site_map

# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(10,10),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
site_map

# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
for index, site in launch_sites_df.iterrows():
    coordinates = [site['Lat'], site['Long']]
    site_name = site['Launch Site']

    # Create a Circle for each launch site

    circle = folium.Circle(coordinates, radius=1000, color='#d35400', fill=True).add_child(folium.Popup(site_name))
    # Create a Marker with DivIcon for the site name
    marker = folium.map.Marker(
        coordinates,
        icon=DivIcon(
            icon_size=(10,10),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % site_name,
        )
    )
    site_map.add_child(circle)
    site_map.add_child(marker)

# Display the map with all launch sites
site_map

marker_cluster = MarkerCluster()

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')
display(spacex_df.tail())

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed,
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color'])
for index, record in spacex_df.iterrows():
    # Create a Marker object with its coordinate and icon
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        popup=record['Launch Site']    )
    marker_cluster.add_child(marker)

# Add marker_cluster to current site_map AFTER all markers have been added to the cluster
site_map.add_child(marker_cluster)

site_map

# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

"""The `spacex_df` has a column called `class` which indicates if a launch was successful (1) or failed (0). We can use this to color the markers. I'll add a new column called `marker_color` to `spacex_df`."""

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
display(spacex_df.head())

"""Now, let's reinitialize the map and add the markers for each launch from `spacex_df`. This will ensure that only the 56 launch markers are displayed. I will use the same `nasa_coordinate` and `zoom_start` as before."""

# Initial the map with the `nasa_coordinate` and `zoom_start`
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# Add a MarkerCluster to the map
marker_cluster = MarkerCluster()
site_map.add_child(marker_cluster)

# For each row in spacex_df data frame, create a Marker object
for index, record in spacex_df.iterrows():
    # Create a Marker object with its coordinate and icon
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        popup=record['Launch Site']
    )
    marker_cluster.add_child(marker)

# Display the updated map
site_map

"""Now that the map has been reinitialized and the correct markers are displayed, let's re-add the `MousePosition` plugin so you can see the coordinates when hovering over the map."""

# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

"""### Plotting a PolyLine between a launch site and a coastline point

Let's assume we want to find the distance from a launch site, for example, `CCAFS SLC-40`, to a nearby coastline point. We will define a sample coastline coordinate and then draw a `PolyLine` on the map between the two points.
"""

# Define the coordinates for CCAFS SLC-40 (from launch_sites_df)
launch_site_lat = 28.563197
launch_site_lon = -80.576820

# Define a sample coastline point (from previous context)
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calculate the distance between the two points
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distance to coastline from CCAFS SLC-40: {distance_coastline:.2f} km")

# Create a PolyLine object between the launch site and the coastline point
points = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]
polyline = folium.PolyLine(locations=points, weight=1, color='blue')

# Add the PolyLine to the site_map
site_map.add_child(polyline)

# Add markers for the launch site and coastline point for clarity
folium.Marker(
    [launch_site_lat, launch_site_lon],
    icon=folium.Icon(color='red'),
    popup="CCAFS SLC-40 Launch Site"
).add_to(site_map)

folium.Marker(
    [coastline_lat, coastline_lon],
    icon=folium.Icon(color='blue'),
    popup="Coastline Point"
).add_to(site_map)

# Re-add Mouse Position to ensure it's displayed on the updated map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

# Display the map
site_map