# -*- coding: utf-8 -*-
"""SQL Notebook for Peer Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jbDfRTRAUm-h4DUoD-en5L8tU0nMSf87
"""

!pip install sqlalchemy==1.3.9
!pip install ipython-sql
!pip install ipython-sql prettytable

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

!pip install -q pandas

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///my_data1.db

import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

# Commented out IPython magic to ensure Python compatibility.
#DROP THE TABLE IF EXISTS

# %sql DROP TABLE IF EXISTS SPACEXTABLE;

# Commented out IPython magic to ensure Python compatibility.
# %sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT DISTINCT Launch_Site FROM SPACEXTABLE;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT * FROM SPACEXTABLE WHERE Launch_Site LIKE 'CCA%' LIMIT 5;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT SUM(PAYLOAD_MASS__KG_) FROM SPACEXTABLE WHERE Customer = 'NASA (CRS)';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEXTABLE WHERE Booster_Version = 'F9 v1.1';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT Date FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (ground pad)' ORDER BY Date ASC LIMIT 1;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT DISTINCT Booster_Version FROM SPACEXTABLE WHERE Landing_Outcome = 'Success (drone ship)' AND PAYLOAD_MASS__KG_ BETWEEN 4000 AND 6000;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT Mission_Outcome, COUNT(Mission_Outcome) AS total_outcomes FROM SPACEXTABLE GROUP BY Mission_Outcome;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT Booster_Version FROM SPACEXTABLE WHERE PAYLOAD_MASS__KG_ = (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXTABLE);

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     substr(Date, 6, 2) AS Month,
#     Landing_Outcome,
#     Booster_Version,
#     Launch_Site
# FROM
#     SPACEXTABLE
# WHERE
#     Landing_Outcome = 'Failure (drone ship)' AND substr(Date, 0, 5) = '2015';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT
#     Landing_Outcome,
#     COUNT(Landing_Outcome) AS Outcome_Count
# FROM
#     SPACEXTABLE
# WHERE
#     Date BETWEEN '2010-06-04' AND '2017-03-20'
# GROUP BY
#     Landing_Outcome
# ORDER BY
#     Outcome_Count DESC;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT DISTINCT Launch_Site FROM SPACEXTABLE;