# -*- coding: utf-8 -*-
"""Web scraping Falcon 9 and Falcon Heavy Launches Records from Wikipedia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmuoh4A2sDKdoKHpVnm0WTYC6kw-wzqO
"""

!pip3 install beautifulsoup4
!pip3 install requests

import sys

import requests
from bs4 import BeautifulSoup
import re
import unicodedata
import pandas as pd

def date_time(table_cells):
    """
    This function returns the data and time from the HTML  table cell
    Input: the  element of a table data cell extracts extra row
    """
    return [data_time.strip() for data_time in list(table_cells.strings)][0:2]

def booster_version(table_cells):
    """
    This function returns the booster version from the HTML  table cell
    Input: the  element of a table data cell extracts extra row
    """
    out=''.join([booster_version for i,booster_version in enumerate( table_cells.strings) if i%2==0][0:-1])
    return out

def landing_status(table_cells):
    """
    This function returns the landing status from the HTML table cell
    Input: the  element of a table data cell extracts extra row
    """
    out=[i for i in table_cells.strings][0]
    return out


def get_mass(table_cells):
    mass=unicodedata.normalize("NFKD", table_cells.text).strip()
    if mass:
        mass.find("kg")
        new_mass=mass[0:mass.find("kg")+2]
    else:
        new_mass=0
    return new_mass


def extract_column_from_header(row):
    """
    This function returns the column name from an HTML table header cell (th).
    It cleans up the text by removing sub-tags like <sup>, <a>, <br>
    and filters out empty names.
    Input: row - a BeautifulSoup Tag object representing a <th> element.
    """
    # Make a copy if you don't want to modify the original tag passed
    # For header extraction, modifying the temporary copy is usually fine.
    # However, if operating on an element directly from soup, it modifies soup.
    # Since this function is called with a copy of the th tag (temp_th in e607d937),
    # modifications are isolated.

    # The function is designed to modify the 'row' object in place,
    # so when used with `temp_th = BeautifulSoup(str(th_element), 'html.parser').find('th')`
    # in `e607d937`, the modifications are done on the `temp_th` object.

    if row.br:
        row.br.extract()
    if row.a:
        row.a.extract()
    if row.sup:
        row.sup.extract()

    # Use get_text() to safely extract and clean the text content
    colunm_name = row.get_text(strip=True)

    # Filter out only empty strings, allowing names with digits or special chars.
    if colunm_name:
        return colunm_name
    return None # Return None for empty items

static_url = "https://en.wikipedia.org/w/index.php?title=List_of_Falcon_9_and_Falcon_Heavy_launches&oldid=1027686922"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/91.0.4472.124 Safari/537.36"
}

response = requests.get(static_url, headers=headers)

response.raise_for_status() # Raise an exception for HTTP errors
print(f"Status Code: {response.status_code}")

soup = BeautifulSoup(response.text, 'html.parser')

html_table = soup.find('table', class_='wikitable plainrowheaders collapsible')
first_launch_table = html_table.find_all('tr')[2]
print(first_launch_table)

column_names = []

# Find the first row (<tr>) in the html_table, which typically contains the headers
first_table_row = html_table.find('tr')

# Apply find_all() function with `th` element on the first_table_row
for th in first_table_row.find_all('th'):
    # It's important to create a temporary copy to avoid modifying the original soup structure
    # when extract_column_from_header is called, as it modifies the tag in-place.
    temp_th = BeautifulSoup(str(th), 'html.parser').find('th')
    name = extract_column_from_header(temp_th)
    if name is not None and len(name) > 0:
        column_names.append(name)

print(column_names)

launch_dict = {key: [] for key in column_names}

# Remove an irrelevant column
# Corrected the key name to match 'Date andtime ()'
del launch_dict['Date andtime ()']

# Added some new columns, ensuring they are initialized as empty lists
# The existing columns from column_names are already initialized above
launch_dict['Version Booster'] = []
launch_dict['Booster landing'] = []
launch_dict['Date'] = []
launch_dict['Time'] = []

# For a fresh run, ensure column_names is re-evaluated and launch_dict is freshly created.

extracted_row = 0
#Extract each table
for table_number,table in enumerate(soup.find_all('table',"wikitable plainrowheaders collapsible")):
   # get table row
    for rows in table.find_all("tr"):
        #check to see if first table heading is as number corresponding to launch a number
        if rows.th:
            if rows.th.string:
                flight_number=rows.th.string.strip()
                flag=flight_number.isdigit()
        else:
            flag=False
        #get table element
        row=rows.find_all('td')
        #if it is number save cells in a dictionary
        if flag:
            extracted_row += 1
            # Flight Number value
            launch_dict['Flight No.'].append(flight_number)

            datatimelist=date_time(row[0])

            # Date value
            date = datatimelist[0].strip(',')
            launch_dict['Date'].append(date)

            # Time value
            time = datatimelist[1]
            launch_dict['Time'].append(time)

            # Booster version
            bv=booster_version(row[1])
            if not bv: # If booster_version function fails to extract
                if row[1].a: # Check if <a> tag exists
                    bv = row[1].a.string
                else: # Fallback to text if no <a> tag
                    bv = row[1].text.strip()
            launch_dict['Version Booster'].append(bv)

            # Launch Site
            if row[2].a:
                launch_site = row[2].a.string
            else:
                launch_site = row[2].text.strip()
            launch_dict['Launch site'].append(launch_site)

            # Payload
            if row[3].a:
                payload = row[3].a.string
            else:
                payload = row[3].text.strip()
            launch_dict['Payload'].append(payload)

            # Payload Mass
            payload_mass = get_mass(row[4])
            launch_dict['Payload mass'].append(payload_mass)

            # Orbit
            if row[5].a:
                orbit = row[5].a.string
            else:
                orbit = row[5].text.strip()
            launch_dict['Orbit'].append(orbit)

            # Customer
            if row[6].a:
                customer = row[6].a.string
            else:
                customer = row[6].text.strip()
            launch_dict['Customer'].append(customer)

            # Launch outcome
            launch_outcome = list(row[7].strings)[0]
            launch_dict['Launchoutcome'].append(launch_outcome) # Corrected key name here

            # Booster landing
            booster_landing = landing_status(row[8])
            launch_dict['Booster landing'].append(booster_landing)

df= pd.DataFrame({ key:pd.Series(value) for key, value in launch_dict.items() })

df.to_csv('spacex_web_scraped.csv', index=False)

df.tail()

"""### Mount Google Drive

First, I will mount your Google Drive to allow saving files to it.
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Save CSV to Google Drive

Now, I will save the `spacex_web_scraped.csv` file to your Google Drive. Please make sure to replace `path/to/your/folder/` with the desired folder path in your Google Drive.
"""

import os

# Define the directory path
directory_path = '/content/drive/My Drive/IBM project'

# Check if the directory exists, and create it if it doesn't
if not os.path.exists(directory_path):
    os.makedirs(directory_path)
    print(f"Directory '{directory_path}' created.")
else:
    print(f"Directory '{directory_path}' already exists.")

Myoutput_path = '/content/drive/My Drive/IBM project/Space X Falcon 9 First Stage Landing Prediction 2.csv'
df.to_csv(Myoutput_path, index=False)
print(f"'Space X Falcon 9 First Stage Landing Prediction 2.csv' has been saved to {Myoutput_path}")

soup.title